server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.100.132:3306/sky_take_out_new?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.100.132
      port: 6379
      password: Redis123!

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

jjwt:
  secret: "12345678901234561234567890123456"
  expiration: 1209600000 # 14 days

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '管理员端口'
      paths-to-match: '/**'
      packages-to-scan: com.luruoyang.controller.admin
    - group: '用户端口'
      paths-to-match: '/**'
      packages-to-scan: com.luruoyang.controller.user

knife4j:
  enable: true
  setting:
    language: zh_cn


#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    org.springframework.jdbc: DEBUG
#    org.mybatis: debug

# aliyun oss
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: luruoyang
    region: cn-hangzhou
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
logging:
  pattern:
    console: "%5p %-40.40logger{39} : %method:%line - %m%n"
