server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.100.132:3306/sky_take_out_new?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: 192.168.100.132
      port: 6379
      password: Redis123!
  cache:
    type: redis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

cangqiong:
  jjwt:
    admin-secret: 12345678901234561234567890123abc
    admin-expiration: 1209600000 # 14 days
    admin-token-name: token
    user-secret-key: 12345678901234561234567890123abc
    user-ttl: 1209600000
    user-token-name: authentication

  wechat:
    auth-url: https://api.weixin.qq.com/sns/jscode2session
    appid: wx718e2a5c0a79ad8a
    secret: 9e62707b606171dde26079f7444ce4d8

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '管理员端口'
      paths-to-match: '/**'
      packages-to-scan: com.luruoyang.controller.admin
    - group: '用户端口'
      paths-to-match: '/**'
      packages-to-scan: com.luruoyang.controller.user

knife4j:
  enable: true
  setting:
    language: zh_cn


#logging:
#  level:
#    com.zaxxer.hikari: DEBUG
#    org.springframework.jdbc: DEBUG
#    org.mybatis: debug

# aliyun oss
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: luruoyang
    region: cn-hangzhou
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
logging:
  pattern:
    console: "%5p %-40.40logger{39} : %method:%line - %m%n"


baidu:
  weather:
    key: ${BAIDU_KEY}

gaode:
  map:
    key: ${GAODE_KEY}