server:
  port: 8080

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sky_take_out_new?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: MySQL123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
  # redis
    redis:
      host: localhost
      port: 6379
      password: Redis123!
# mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml

# JWT
jjwt:
  secret: "12345678901234561234567890123456"
  expiration: 1209600000 # 14 days

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.luruoyang.controller

#knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


# aliyun oss
aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT}
    bucket-name: ${OSS_BUCKET_NAME}
    region: ${OSS_REGION}
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}